Fully "functional dummy"
We've reached NotImplementedError!

  File "/Users/alexclark/Developer/test/test-django-zodb/.venv/lib/python3.12/site-packages/django/db/backends/base/introspection.py", line 65, in get_table_list
    raise NotImplementedError(
NotImplementedError: subclasses of BaseDatabaseIntrospection may require a get_table_list() method
make: *** [django-migrate-default] Error 1